version: "3"
services:
  mongodb:
    image: mongo

  simple_bot_handler:
    build: .
    depends_on:
      - mongodb
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      MONGODB_HOST: "mongodb"
      DATABASE_NAME: "simple_bot_handler"
