name: Continuos Integration
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '***NO_CI***')"
    steps:
      - uses: actions/checkout@v2
      - run: ls -laR

      - name: Set branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade build bumpversion

      - name: Run build
        run: python3 -m build

      - name: Publish package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Bump version for next release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          version=$(python3 ./setup.py --version)
          echo $version

          bumpversion --allow-dirty --current-version $version patch ./setup.py
          newversion=$(python3 ./setup.py --version)
          echo $newversion

          git config --global user.email "build_agent@example.com"
          git config --global user.name "GitHub Build Agent"

          git config --list

          git add ./setup.py
          git commit -m "Bumped pypi version ***NO_CI***"
          git push origin ${{ steps.vars.outputs.short_ref }} --porcelain
