name: Continuos Integration
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - run: which python3
      - run: pip3 install --upgrade pip
      - run: pip3 install --upgrade build
      - run: python3 -m build
